app:
  addr: :8080
  mode: release
mysql:
  host: localhost:3306
  user: csqsiew
  dbname: singlishwords
  password: 123456
  options:
    - parseTime=True
redis:
  host: localhost:6379
  password:
  db: 0
swagger:
  enable: true
  path: /_/swagger/*any