package main

import (
	"github.com/fvbock/endless"
	"singlishwords/router"

	_ "singlishwords/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Singlish words API document
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath
func main() {
	r := router.GetRouter()
	_ = endless.ListenAndServe(":8080", r)
}
