// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/answer": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Answer"
                ],
                "summary": "Post an answer",
                "parameters": [
                    {
                        "description": "answer with 3 associations",
                        "name": "answer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/answer.paramPostSingleAnswer"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Answer"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiv1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/answers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Answer"
                ],
                "summary": "Get all answers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "default=10000",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Answer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiv1.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Answer"
                ],
                "summary": "Post respondent information and answers together",
                "parameters": [
                    {
                        "description": "the information",
                        "name": "respondent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/answer.paramPostRespondentWithAnswers"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Respondent"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiv1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/questions": {
            "get": {
                "description": "Get a list of questions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Get a list of questions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Will return limit number of questions, default=8",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Question"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiv1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/respondent": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Respondent"
                ],
                "summary": "Post a respondent information",
                "parameters": [
                    {
                        "description": "respondent information",
                        "name": "respondent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/respondent.postRespondentBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Respondent"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiv1.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Respondent"
                ],
                "summary": "Patch emails",
                "parameters": [
                    {
                        "description": "respondent information",
                        "name": "respondent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/respondent.patchRespondentBody"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiv1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/respondents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Respondent"
                ],
                "summary": "Get all respondents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "default=10000",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Respondent"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiv1.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "answer.paramPostRespondentWithAnswers": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "countryOfBirth": {
                    "type": "string"
                },
                "countryOfResidence": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "question": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "word": {
                                        "type": "string"
                                    }
                                }
                            },
                            "response": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "timeOnPage": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "education": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "ethnicity": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "isNative": {
                    "type": "string"
                },
                "languagesSpoken": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "answer.paramPostSingleAnswer": {
            "type": "object",
            "properties": {
                "association1": {
                    "type": "string"
                },
                "association2": {
                    "type": "string"
                },
                "association3": {
                    "type": "string"
                },
                "questionId": {
                    "type": "integer"
                },
                "respondentId": {
                    "type": "integer"
                },
                "timeSpend": {
                    "type": "integer"
                }
            }
        },
        "apiv1.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "model.Answer": {
            "type": "object",
            "properties": {
                "association1": {
                    "type": "string"
                },
                "association2": {
                    "type": "string"
                },
                "association3": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "questionId": {
                    "type": "integer"
                },
                "respondentId": {
                    "type": "integer"
                },
                "timeSpend": {
                    "type": "integer"
                }
            }
        },
        "model.Question": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "model.Respondent": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "countryOfBirth": {
                    "type": "string"
                },
                "countryOfResidence": {
                    "type": "string"
                },
                "education": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "ethnicity": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isNative": {
                    "type": "string"
                },
                "languagesSpoken": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "respondent.patchRespondentBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "respondent.postRespondentBody": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "countryOfBirth": {
                    "type": "string"
                },
                "countryOfResidence": {
                    "type": "string"
                },
                "education": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "ethnicity": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "isNative": {
                    "type": "string"
                },
                "languagesSpoken": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Singlish words API document",
	Description: "This is a sample server Petstore server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
