basePath: /api/v1
definitions:
  answer.paramPostRespondentWithAnswers:
    properties:
      age:
        type: integer
      countryOfBirth:
        type: string
      countryOfResidence:
        type: string
      data:
        items:
          properties:
            question:
              properties:
                id:
                  type: integer
                word:
                  type: string
              type: object
            response:
              items:
                type: string
              type: array
            timeOnPage:
              type: integer
          type: object
        type: array
      education:
        type: string
      email:
        type: string
      endTime:
        type: string
      ethnicity:
        type: string
      gender:
        type: string
      isNative:
        type: string
      languagesSpoken:
        type: string
      startTime:
        type: string
    type: object
  answer.paramPostSingleAnswer:
    properties:
      association1:
        type: string
      association2:
        type: string
      association3:
        type: string
      questionId:
        type: integer
      respondentId:
        type: integer
      timeSpend:
        type: integer
    type: object
  apiv1.ErrorResponse:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  model.Answer:
    properties:
      association1:
        type: string
      association2:
        type: string
      association3:
        type: string
      id:
        type: integer
      questionId:
        type: integer
      respondentId:
        type: integer
      timeSpend:
        type: integer
    type: object
  model.Question:
    properties:
      id:
        type: integer
      word:
        type: string
    type: object
  model.Respondent:
    properties:
      age:
        type: integer
      countryOfBirth:
        type: string
      countryOfResidence:
        type: string
      education:
        type: string
      email:
        type: string
      endTime:
        type: string
      ethnicity:
        type: string
      gender:
        type: string
      id:
        type: integer
      isNative:
        type: string
      languagesSpoken:
        type: string
      startTime:
        type: string
    type: object
  respondent.patchRespondentBody:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
  respondent.postRespondentBody:
    properties:
      age:
        type: integer
      countryOfBirth:
        type: string
      countryOfResidence:
        type: string
      education:
        type: string
      email:
        type: string
      endTime:
        type: string
      ethnicity:
        type: string
      gender:
        type: string
      isNative:
        type: string
      languagesSpoken:
        type: string
      startTime:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Singlish words API document
  version: "1.0"
paths:
  /answer:
    post:
      parameters:
      - description: answer with 3 associations
        in: body
        name: answer
        required: true
        schema:
          $ref: '#/definitions/answer.paramPostSingleAnswer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Answer'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiv1.ErrorResponse'
      summary: Post an answer
      tags:
      - Answer
  /answers:
    get:
      parameters:
      - description: default=10000
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Answer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiv1.ErrorResponse'
      summary: Get all answers
      tags:
      - Answer
    post:
      parameters:
      - description: the information
        in: body
        name: respondent
        required: true
        schema:
          $ref: '#/definitions/answer.paramPostRespondentWithAnswers'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Respondent'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiv1.ErrorResponse'
      summary: Post respondent information and answers together
      tags:
      - Answer
  /questions:
    get:
      description: Get a list of questions
      parameters:
      - description: Will return limit number of questions, default=8
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Question'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiv1.ErrorResponse'
      summary: Get a list of questions
      tags:
      - Questions
  /respondent:
    patch:
      parameters:
      - description: respondent information
        in: body
        name: respondent
        required: true
        schema:
          $ref: '#/definitions/respondent.patchRespondentBody'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiv1.ErrorResponse'
      summary: Patch emails
      tags:
      - Respondent
    post:
      parameters:
      - description: respondent information
        in: body
        name: respondent
        required: true
        schema:
          $ref: '#/definitions/respondent.postRespondentBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Respondent'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiv1.ErrorResponse'
      summary: Post a respondent information
      tags:
      - Respondent
  /respondents:
    get:
      parameters:
      - description: default=10000
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Respondent'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiv1.ErrorResponse'
      summary: Get all respondents
      tags:
      - Respondent
swagger: "2.0"
